# Generated by Django 5.1.2 on 2024-10-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submission_time", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("STARTED", "STARTED"),
                            ("SUCCESS", "SUCCESS"),
                            ("FAILURE", "FAILURE"),
                            ("RETRY", "RETRY"),
                            ("REVOKED", "REVOKED"),
                        ],
                        default="PENDING",
                        max_length=255,
                    ),
                ),
                ("result", models.TextField(blank=True, null=True)),
                ("input_file", models.FileField(upload_to="uploads/")),
                (
                    "output_file",
                    models.FileField(blank=True, null=True, upload_to="converted/"),
                ),
                ("conversion_format", models.CharField(max_length=10)),
                ("task_id", models.UUIDField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
